# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: schwerathletikmannheim2018ev
# "service" is the name of this project. This will also be added to your AWS resource names.
service: slack-service-bot

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs20.x
  timeout: 29
  environment:
    # Slack config
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    # App config
    APP_ADMIN: ${env:APP_ADMIN}
    PORT: ${env:PORT}
    APP_ADMIN_CHANNEL: ${env:APP_ADMIN_CHANNEL}
    # Staette config
    STAETTE_CHANNEL: ${env:STAETTE_CHANNEL}
    CRONJOB_LOG_TO_ADMIN: ${env:CRONJOB_LOG_TO_ADMIN}
    # Signatures config
    SIGNATURE_SIGNING_SECRET: ${env:SIGNATURE_SIGNING_SECRET}
    SIGNATURE_HEADER_NAME: ${env:SIGNATURE_HEADER_NAME}
    APPLICATION_FORM_TEMPLATE_ID: ${env:APPLICATION_FORM_TEMPLATE_ID}
    SIGNATURE_WORKFLOW_SLACK_WEBHOOK: ${env:SIGNATURE_WORKFLOW_SLACK_WEBHOOK}
    # Arbeitsstunden config
    SPREADSHEET_ID_MASTERDATA: ${env:SPREADSHEET_ID_MASTERDATA}
    GOOGLE_SERVICE_ACC_EMAIL: ${env:GOOGLE_SERVICE_ACC_EMAIL}
    GOOGLE_SERVICE_ACC_PRIVATE_KEY: ${env:GOOGLE_SERVICE_ACC_PRIVATE_KEY}

package:
  patterns:
    - '!aws/**'
    - '!images/**'
    - '!.github/**'
    - '!.eslintrc.json*'
    - '!.prettierrc'
    - '!example.env'

functions:
  slack-service-bot:
    handler: ./src/app.handler
    events:
      - http:
          path: slack/events
          method: post
  slack-service-bot-staette-cleanup:
    handler: ./src/staette/cleanup.run
    events:
      - schedule: cron(0 0 * * ? *) ## Runs every day at midnight UTC
  slack-service-bot-masterdata-notification:
    handler: ./src/general/masterdata/notifications.run
    events:
      - schedule:
          method: scheduler
          rate:
            - cron(0 9 * * ? *) ## Runs every day at 9:00 Berlin time
          timezone: Europe/Berlin
  slack-service-bot-signature-webhook:
    handler: ./src/signatures/webhooks.handler
    events:
      - http:
          path: docuseal/webhook
          method: post

plugins:
  - serverless-offline
