# EXAMPLE FILE FOR Nginx Proxy Manager
version: "3.9"

services:
  npm_db:
    image: mysql:5.7
    container_name: npm_db
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: #
      MYSQL_DATABASE: npm
      MYSQL_USER: #
      MYSQL_PASSWORD: #

  npm:
    depends_on:
      - npm_db
    image: "jc21/nginx-proxy-manager:latest"
    container_name: npm
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_MYSQL_HOST: npm_db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: #
      DB_MYSQL_PASSWORD: #
      DB_MYSQL_NAME: npm
      DISABLE_IPV6: "true"
    volumes:
      - ./data:/data
      - ./logs:/var/log/nginx
      - ./letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - proxy
      - default

networks:
  proxy:
    name: proxy
    driver: bridge
